[default.extend-words]
ist = "ist"
acn = "acn"
usera = "usera"
multline = "multline"
Winn = "Winn"
nd = "nd"
thm = "thm"

[files]
extend-exclude = ["CHANGELOG.md", "main.bib", "latexmkrc", "ruff.toml"]
