name: 🐞 提交一个问题
description: 来帮助我们一起完善 BIThesis 吧！
title: "[Bug]: 在这里概括你的问题"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你抽出宝贵的时间来提交这个问题！
        在提交问题前，请尝试使用我们[最新版本的模板](https://github.com/BITNP/BIThesis/releases)复现问题。
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请描述你遇到的问题。
      placeholder: 清晰而简明地描述我所遇到的问题。
    validations:
      required: true
  - type: textarea
    id: what-is-expected
    attributes:
      label: 你期望的结果
      description: 提供一下你期望的结果。
      placeholder: 简述我期望得到的正确结果。
    validations:
      required: false
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: 问题复现的步骤（或者截图）
      description: 我们如何才能帮你复现这个问题? （如果问题比较复杂，请考虑提供一个能够供我们编译的、可复现的示例。）
      placeholder: |
        1. 打开……
        2. 点击……
        3. 移动到……
        4. 就能看见这个问题……

        ```latex
        % 复杂问题可提供代码示例
        ```
    validations:
      required: true
  - type: dropdown
    id: templates
    attributes:
      label: BIThesis 模板
      description: 你遇到问题的模板有哪些？
      multiple: true
      options:
        - 硕博·学位论文 — graduate-thesis
        - 本科·毕业设计或读书报告 — undergraduate-thesis[-en]、paper-translation、reading-report
        - 演示文档 — presentation-slide
        - 实验报告 — lab-report
  - type: dropdown
    id: os
    attributes:
      label: 操作系统或平台
      description: 你使用的操作系统或平台是什么？
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Overleaf等在线平台
    validations:
      required: false
  - type: input
    id: software
    attributes:
      label: LaTeX 发行版以及发行年份
      placeholder: TexLive 2024
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 日志信息（可选）
      description: 请复制并粘贴任何相关的日志输出。这将被自动格式化为代码，所以不需要“`”符号。
      render: shell
