name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
            make test

  check_typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling of bithesis.dtx
        uses: crate-ci/typos@master

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
